package crawler.statemachine.guistatemachine;

public enum Event {
    DISPLAY_CRAWLED_PAGE, FINISH_DISPLAYING, START_CRAWLING, INTERRUPT_CRAWLING, CRAWLING_STARTED, EXPORT_CRAWLED_DATA,
    FAILED_T0_START_CRAWLING
}
